### ISSUE TITLE
HARREJLEN EL VUUUUUC

### ISSUE THREAD

**Issue by Ynozzar** [Ynozzar/Test#3]

**Comment by Ynozzar** [comment]
bengaaaaa harreglenlooo por tutatiiiiiiiiiiiiiis

**Comment by Ynozzar** [comment]
hestoi travajando en la 2

**Comment by Ynozzar** [comment]
reemplazo a félix rodrijez de la foint

**Comment by Ynozzar** [comment]
apagad el consolador bivrador

**Comment by Imdeeo** [comment]
Bug va con uve alta inculto

**Comment by Imdeeo** [comment]
...

**Comment by Imdeeo** [comment]
No t'aclaras!
